Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -77,18 +77,14 @@ jobs:
                 name: Assert build quality against security standards
                 command: |
                     BUILD_RESULT=$(curl -X GET "https://www.shiftleft.io/api/v3/public/org/$SHIFTLEFT_ORG_ID/app/$APP_NAME/tag/branch/$CIRCLE_BRANCH/build" -H "Authorization: Bearer $SHIFTLEFT_API_TOKEN" -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Host: www.shiftleft.io' -H 'accept-encoding: text/plain, deflate' -H 'cookie: Cookie_3=value' -s -b Cookie_3=value)
-                    echo "Build result - $BUILD_RESULT"
-                    SUCCESS=$(echo $BUILD_RESULT | grep "success")
-                    echo "Success - $SUCCESS"
-                    if [ -z "$SUCCESS" ]; then
+                    if [ $(echo $BUILD_RESULT | grep "success") ]; then
+                        PR_COMMENT="ShiftLeft did not detect any vulnerabilities that violate policy. This PR can be merged."
+                    else
                         URL="https://shiftleft.io/"
                         URL+=$(echo $OUTPUT | jq -r '.errorDetails')
                         echo "URL- $URL"
                         PR_COMMENT="ShiftLeft found vulnerabilities that violate policy. Go here for more details - $URL"
-                    else
-                        PR_COMMENT="ShiftLeft did not detect any vulnerabilities that violate policy. This PR can be merged."
                     fi
-                    echo "PR Comment - $PR_COMMENT"
 
             - run:
                 name: Adding comment to the PR
@@ -99,11 +95,16 @@ jobs:
                         PR_NUMBER=$(echo $CIRCLE_PULL_REQUEST | cut -d '/' -f7)
                         curl -X POST https://api.github.com/repos/$PR_USER/$PR_REPO/issues/$PR_NUMBER/comments -H "Authorization: token $GH_AUTH_TOKEN" -d "{\"body\": \"$PR_COMMENT\"}"
 
-                        if [ -z "$SUCCESS" ]; then
+                        if [ $(echo $BUILD_RESULT | grep "success") ]; then
+                            echo "Failing the build since PR violates security policy"
                             exit 1
                         fi
                     else
-                        echo "No PR information. Was this a commit directly to the master branch?"
+                        echo "No PR information. Was this a commit/merge to the master branch?"
+                         if [ $(echo $BUILD_RESULT | grep "success") ]; then
+                            echo "Failing the build since commit/merge violates security policy"
+                            exit 1
+                        fi
                     fi
                     
 workflows:
